name: Build JAR and Create Docker Image

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  build_and_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean build

      - name: Verify JAR file
        run: ls -al build/libs/

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t jersey-async-rest/jersey_async_app:latest .